apiVersion: v1
kind: Service
metadata:
  name: solomon-app-svc
  namespace: solomon-ns
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "classic"
spec:
  type: LoadBalancer
  selector:
    app: solomon-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
